export const USER_LOGIN = "USER_LOGIN";
export const UPDATE_CHAT_MESSAGES = 'UPDATE_CHAT_MESSAGES';
export const RESET_CHAT = 'RESET_CHAT';
export const GET_CHATS_MESSAGES = 'GET_CHATS_MESSAGES';
export const GET_CHAT_HEADS = 'GET_CHAT_HEADS';
export const RESET_USERS_BY_TYPE = 'RESET_USERS_BY_TYPE';
export const RESET_ECLASS = 'RESET_ECLASS';
export const GET_ECLASSES = 'GET_ECLASSES';
export const UPDATE_ECLASS = 'UPDATE_ECLASS';
export const GET_USERS_BY_TYPES = 'GET_USERS_BY_TYPES';
export const GET_SCHEDULE_TYPES = 'GET_SCHEDULE_TYPES';
export const GET_FILTER_SCHEDULE_LIST = 'GET_FILTER_SCHEDULE_LIST';
export const RESET_GET_FILTER_SCHEDULE_LIST = 'RESET_GET_FILTER_SCHEDULE_LIST';
export const IS_AUTH = 'IS_AUTH';
export const SET_ROLE = 'SET_ROLE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_STORE_CART = 'UPDATE_STORE_CART';
export const ADD_PAYMENT_CARD = 'ADD_PAYMENT_CARD';
export const IS_BOOKING_CONFIRM = 'IS_BOOKING_CONFIRM';
export const GET_SPORT_TYPES = 'GET_SPORT_TYPES';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_TEAMS_DATA = 'GET_TEAMS_DATA';
export const TEAM_DETAILS = 'TEAM_DETAILS';
export const GET_TEAMMATES_DATA = 'GET_TEAMMATES_DATA';
export const GET_USERINFO_DATA = 'GET_USERINFO_DATA';
export const GET_FOLLOWERS_DATA = 'GET_FOLLOWERS_DATA';
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const GET_STORE_PRODUCTS = 'GET_STORE_PRODUCTS';
export const GET_STORE_PRODUCTSLIST = 'GET_STORE_PRODUCTSLIST';
export const UPDATE_STORE_PRODUCTS = 'UPDATE_STORE_PRODUCTS';
export const DELETE_STORE_PRODUCTS = 'DELETE_STORE_PRODUCTS';
export const GET_FOLLOWING_DATA = 'GET_FOLLOWING_DATA';
export const RESET_FOLLOWING_DATA = 'RESET_FOLLOWING_DATA';
export const GET_FOLLOWER_DATA = 'GET_FOLLOWER_DATA';
export const RESET_FOLLOWER_DATA = 'RESET_FOLLOWER_DATA';
export const FOLLOW_USER = 'FOLLOW_USER';
export const GET_COACHES_DATA = 'GET_COACHES_DATA';
export const SET_COACH_POSITION = 'SET_COACH_POSITION';
export const RESET_COACHES_DATA = 'RESET_COACHES_DATA';
export const GET_COACH_SESSIONS = 'GET_COACH_SESSIONS';
export const RESET_COACH_SESSIONS = 'RESET_COACH_SESSIONS';
export const GET_COACH_SESSION_DETAIL = 'GET_COACH_SESSION_DETAIL';
export const PLAYER_REQUEST_TEAM = 'PLAYER_REQUEST_TEAM';
export const GET_NOTIFICATION_BY_USER = 'GET_NOTIFICATION_BY_USER';
export const RESET_NOTIFICATION_BY_USER = 'RESET_NOTIFICATION_BY_USER';
export const GET_INVITATION_BY_USER = 'GET_INVITATION_BY_USER';
export const RESET_INVITATION_BY_USER = 'RESET_INVITATION_BY_USER';
export const PLAYER_REQUEST_APPROVE = 'PLAYER_REQUEST_APPROVE';
export const POST_CREATE = 'POST_CREATE';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_LIKE = 'POST_LIKE';
export const POST_UPDATE = 'POST_UPDATE';
export const POST_REMOVE = 'POST_REMOVE';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const RESET_POST_COMMENTS = 'RESET_POST_COMMENTS';

export const GET_COACH_BOOKING = 'GET_COACH_BOOKING';
export const GET_BOOKING_HISTORY = 'GET_BOOKING_HISTORY';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const GET_PAYMENT_CARDS = 'GET_PAYMENT_CARDS';
export const SEARCH_ALL_USERS = 'SEARCH_ALL_USERS';
export const RESET_SEARCH_ALL_USERS = 'RESET_SEARCH_ALL_USERS';

export const GET_HIGHLIGHTS_DATA = 'GET_HIGHLIGHTS_DATA';
export const RESET_HIGHLIGHTS_DATA = 'RESET_HIGHLIGHTS_DATA';

export const GET_MY_HIGHLIGHTS_DATA = 'GET_MY_HIGHLIGHTS_DATA';
export const RESET_MY_HIGHLIGHTS_DATA = 'RESET_MY_HIGHLIGHTS_DATA';

export const GET_FACILITY_DATA = 'GET_FACILITY_DATA';
export const RESET_FACILITY_DATA = 'RESET_FACILITY_DATA';
export const GET_LEAGUE_DETAIL = 'GET_LEAGUE_DETAIL';
export const GET_SCHEDULES_DATA = 'GET_SCHEDULES_DATA';
export const RESET_SCHEDULES_DATA = 'RESET_SCHEDULES_DATA';

export const GET_POST_BY_USER = 'GET_POST_BY_USER';
export const DELETE_LEAGUE = 'DELETE_LEAGUE';

export const GET_LEAGUE_HISTORY = 'GET_LEAGUE_HISTORY';

export const GET_MESH_CALENDER = 'GET_MESH_CALENDER';
export const LOGOUT = 'LOGOUT';
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const GET_COLORS = "GET_COLORS";
